In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a1 = np.array([[1, 2, 3],
               [4, 5, 6]])

In [4]:
a2 = np.array([[[1,2,3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [8]:
print(a.shape); print(a1.shape); print(a2.shape)

(3,)
(2, 3)
(2, 3, 3)


In [9]:
a.ndim, a1.ndim, a2.ndim

(1, 2, 3)

In [10]:
a.size, a1.size, a2.size

(3, 6, 18)

In [11]:
#Create a Dataframe from numpy
import pandas as pd

df = pd.DataFrame(a1)
df

0  1  2
0  1  2  3
1  4  5  6

In [12]:
zeros = np.zeros(4)

In [13]:
zeros

array([0., 0., 0., 0.])

In [14]:
zeros1 = np.zeros((2, 3))

In [15]:
zeros1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0, 10, 2)

In [19]:
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [21]:
random_array

array([[7, 4, 0, 1, 2],
       [6, 4, 9, 6, 4],
       [6, 6, 5, 3, 6]])

In [22]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.48479411, 0.27307007, 0.97149035],
       [0.21918954, 0.19894725, 0.03087602],
       [0.03165657, 0.68413986, 0.80867575],
       [0.68747803, 0.11111283, 0.33479315],
       [0.73363354, 0.4548015 , 0.17668612]])

In [23]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.19685187, 0.93546308, 0.45401703],
       [0.81984862, 0.63048308, 0.04314179],
       [0.87225535, 0.06778373, 0.59850431],
       [0.79590798, 0.26997355, 0.64277192],
       [0.19883646, 0.13748009, 0.11347079]])

## Numpy random seed

In [30]:
# Try running this cell multiple times
np.random.seed(0)
random_arr = np.random.randint(10, size=(5, 3))
random_arr

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

Notice that the array isn't changing

In [32]:
np.random.seed(43)
random_arr2 = random_arr = np.random.randint(10, size=(5, 3))
random_arr

array([[4, 0, 1],
       [5, 0, 3],
       [1, 2, 7],
       [0, 3, 2],
       [9, 1, 2]])

This works, no matter what the number is in the seed

The main goal of the seed is that if we share our work with another person or people, they will always have the same random number as mine

## Indexing

In [34]:
a[0]

1

In [35]:
a1[0]

array([1, 2, 3])

In [36]:
a2[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a[:2]

array([1, 2])

In [38]:
a1[:2, :2]

array([[1, 2],
       [4, 5]])

In [39]:
a2[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

## Dot Product

In [3]:
import numpy as np
np.random.seed(0)
# Creating a dataset
jar = np.random.randint(20, size=(5,3))
jar

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [21]:
import pandas as pd
jars = pd.DataFrame(jar, index=['Mon', 'Tue', 'Wed', 'Thur', 'Fri'], columns=['Almond', 'Peanut', 'Cashew'])
jars

Almond  Peanut  Cashew
Mon       12      15       0
Tue        3       3       7
Wed        9      19      18
Thur       4       6      12
Fri        1       6       7

In [19]:
price = np.array([10, 8, 12])

In [20]:
prices = pd.DataFrame(price.reshape(1, 3), index=['Price'], columns=['Almond', 'Peanut', 'Cashew'])
prices

Almond  Peanut  Cashew
Price      10       8      12

In [22]:
total_sales = np.dot(jar, price.reshape(1, 3).T)

In [23]:
jars['Total sales'] = total_sales

In [24]:
jars

Almond  Peanut  Cashew  Total sales
Mon       12      15       0          240
Tue        3       3       7          138
Wed        9      19      18          458
Thur       4       6      12          232
Fri        1       6       7          142

In [25]:
jars.shape, prices.shape

((5, 4), (1, 3))

In [31]:
butter_prices = prices.dot(jars.drop('Total sales', axis=1).T)
# you can also use dot product on the dataframe if their shape are compatible

In [30]:
butter_prices

Mon  Tue  Wed  Thur  Fri
Price  240  138  458   232  142

In [32]:
jars['Total sales'] = butter_prices.T

In [33]:
jars

Almond  Peanut  Cashew  Total sales
Mon       12      15       0          240
Tue        3       3       7          138
Wed        9      19      18          458
Thur       4       6      12          232
Fri        1       6       7          142

## Sorting

In [44]:
tmp = np.random.randint(10, size=(3, 5))

In [45]:
tmp

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1]])

In [46]:
np.sort(tmp)

array([[0, 0, 2, 4, 7],
       [4, 5, 5, 6, 8],
       [1, 1, 4, 8, 9]])

In [51]:
tmp

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1]])

In [52]:
np.argsort(tmp)

array([[2, 3, 1, 4, 0],
       [4, 0, 1, 2, 3],
       [0, 4, 1, 3, 2]], dtype=int64)

In [54]:
np.argsort(np.array([1, 2, 3, 4]))

array([0, 1, 2, 3], dtype=int64)

In [55]:
tmp

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1]])

In [57]:
np.argsort(tmp) # np.argsort is index sorting that returns the indices that would sort an array.

array([[2, 3, 1, 4, 0],
       [4, 0, 1, 2, 3],
       [0, 4, 1, 3, 2]], dtype=int64)

In [61]:
np.argmax(tmp) # returns the index of an max number

12

In [62]:
np.argmin(tmp) # returns the index of an min number

2

In [60]:
tmp

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1]])

In [63]:
np.argmax(tmp, axis=1)

array([0, 3, 2], dtype=int64)

In [65]:
np.argmin(tmp, axis=1)

array([2, 4, 0], dtype=int64)

## Turning image into numpy array

In [67]:
from matplotlib.image import imread

panda = imread('panda.png')
print(type(panda))

<class 'numpy.ndarray'>


In [68]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [69]:
panda.shape, panda.ndim

((2330, 3500, 3), 3)

<img src='dog-photo.png'/>

In [72]:
# <img src='dog-photo'/>